# Generated by Django 3.2.8 on 2021-10-30 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(blank=True, max_length=50, verbose_name='Праздник')),
                ('adresat', models.CharField(blank=True, max_length=500, verbose_name='Кому')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name='Лет')),
                ('kem_prihodit', models.CharField(blank=True, max_length=50, verbose_name='Кем приходится')),
                ('you', models.CharField(blank=True, choices=[('ty', 'Ты'), ('vy', 'Вы')], max_length=2)),
                ('about', models.TextField(blank=True, verbose_name='Инфо для стихов')),
                ('wishes', models.CharField(blank=True, max_length=300, verbose_name='Пожелания')),
                ('style', models.CharField(blank=True, choices=[('uva', 'Уважительном'), ('shu', 'Шуточном'), ('vos', 'Восхваляющем'), ('lir', 'Лирическом')], max_length=3)),
                ('how_many', models.CharField(blank=True, choices=[('one', 'От одного человека'), ('few', 'От нескольких')], max_length=3)),
                ('deadline', models.CharField(blank=True, max_length=50, verbose_name='Срок')),
                ('special', models.CharField(blank=True, max_length=300, verbose_name='Особые пожелания')),
                ('on_site', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Ваше имя')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('Email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
            ],
            options={
                'verbose_name': 'Заказ на стихи',
                'verbose_name_plural': 'Заказы на стихи',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('description', models.TextField(verbose_name='Описание раздела')),
                ('topic_photo', models.ImageField(blank=True, default='', upload_to='images', verbose_name='Фото')),
                ('topic_slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Stih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Описание заказа')),
                ('stih_title', models.CharField(max_length=250, verbose_name='Название')),
                ('stih_text', models.TextField(verbose_name='Текст')),
                ('stih_photo', models.ImageField(blank=True, default='', upload_to='images', verbose_name='Фото')),
                ('stih_slug', models.SlugField(max_length=70, unique=True)),
                ('dateUploaded', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата обновления')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stihinazakaz.topic')),
            ],
            options={
                'verbose_name': 'стихотворение',
                'verbose_name_plural': 'стихи',
                'ordering': ['-dateUploaded'],
            },
        ),
    ]
